### ISSUE TITLE
Builtin Banner++ Support

### ISSUE THREAD

**Issue by DaFuqs** [TheEpicBlock/flagbric#3]
Banner++ seems to have not been updated for quite some time now, albeit there is a pull request to 1.18.2 by @byquanton (https://github.com/kvverti/banner-plus-plus/pull/13) who also maintains a fork of flagbric.
Then there is the flagbric port by @Sunconure11, including Banner++ functionality into flagbric.

I would love to add custom banner patterns into Spectrum and using Banner++/Flagbric seems like the perfect way to do so. Banner++ seems to not get an official update soon. So my question basically is: Will flagbric include the ability to create new banners via other mods at some time like Sunconures branch does, or am I out of luck?

(sorry for the pings everyone!)

**Comment by TheEpicBlock** [comment]
If a mod wants to add custom banners they will not want to have to include flagbric with it. After all, flagbric is completely unrelated to Banners++. It's just that flagbric adds compat with it. So it should stay as its own library.
I wouldn't mind taking over banners++, but I'm assuming their dev just hasn't had the time to check out the pr yet.

**Comment by TheEpicBlock** [comment]
Byquantum's pr seems to have some checkstyle issues, so I've now made a fork over at <https://github.com/TheEpicBlock/banner-plus-plus>. I've also notified the banner++ dev of this but they're busy at the moment. For now you I've published my fork over at:
```groovy
maven {
	url "https://maven.theepicblock.nl"
}
```
with the dependency string being
```
modImplementation "io.github.fablabsmc:bannerpp:2.0.6-teb.1+mc.1.18.2"
```
At some point the official banner++ will be updated and you can switch to that. I'll also push an update to Flagbric which will work with this (and which should also keep working once the official version is out)

**Comment by DaFuqs** [comment]
Awesome! Time to design some banners, then.
